### ISSUE TITLE
Links don't work in chatbot emulator

### ISSUE THREAD

**Issue by BridgetManley** [AscendantDesign/Scaffold#18]
Attaching a link to a node, either in the incoming or outgoing socket, prevents the node from loading in the emulator. 

- If the link is attached to the incoming socket, then the learner's response to the previous question doesn't show.

- If the link is attached to the outgoing socket, then the content for that node doesn't show

**Comment by danielanywhere** [comment]
ADO1917.

**Comment by danielanywhere** [comment]
DEP20201128.1522 - Links now appear at the question card level on chatbot emulator. You can attach a link at any level, but it is currently only useful at the question. This will probably change in the near future. Either the link won't be eligible for addition at the socket level, or its content will be employed on socket-type entities.

**Comment by danielanywhere** [comment]
Oops! Not closed until executable is released.

**Comment by danielanywhere** [comment]
Fixed by [Technology Preview 1.3c](https://github.com/AscendantDesign/Scaffold/releases/tag/v0.2020.1130-preview.1.3c)
