### ISSUE TITLE
Request: Starting the emulator from a specific node

### ISSUE THREAD

**Issue by BridgetManley** [AscendantDesign/Scaffold#19]
Currently, the emulator begins at the beginning of the conversation. Is there a way to make the chatbot emulator start from a specific node instead? This will make it easier to preview a specific part of the conversation when working out kinks in the instructional design.

**Comment by danielanywhere** [comment]
ADO1918.

**Comment by danielanywhere** [comment]
You can now start the chatbot emulator from the selected node. Use the menu option Tools / Chatbot Emulator / Emulate From Selected Node.

**Comment by danielanywhere** [comment]
Addressed by [Technology Preview 1.3c](https://github.com/AscendantDesign/Scaffold/releases/tag/v0.2020.1130-preview.1.3c)
