### ISSUE TITLE
Ending conversation on an output socket

### ISSUE THREAD

**Issue by BridgetManley** [AscendantDesign/Scaffold#27]
It would be helpful to have the option to terminate a conversation or lesson on one of the output sockets. In conversation-based learning, this would allow the learner to have the "last word" and tell the bot goodbye.

**Comment by danielanywhere** [comment]
DEP20201214.1156 - You can end the conversation on an output socket. If no connection is made to a following node, a user response is allowed, but no server response follows.

**Comment by danielanywhere** [comment]
Published in v0.2020.1214.
