### ISSUE TITLE
Images not displaying in emulator

### ISSUE THREAD

**Issue by BridgetManley** [AscendantDesign/Scaffold#58]
In the current version, when images are attached to an answer socket, they don't display in the emulator.

**Comment by danielanywhere** [comment]
DEP20201229.1624 - This occurs when emulating from a node that has the media on the output sockets. Temporary workaround: emulate from at least one node prior to the node containing the media.

**Comment by danielanywhere** [comment]
DEP20201230.0804 - The allowance for output media on buttons has now been specified in the start-up routine.

**Comment by danielanywhere** [comment]
Release in v0.2020.1230.
