### ISSUE TITLE
Responses appearing incorrectly on node

### ISSUE THREAD

**Issue by BridgetManley** [AscendantDesign/Scaffold#64]
In the files "U1_L1.node.jsn" and "Slack_U1_L1.node.jsn," the responses for the third-to-last node are appearing incorrectly. (This node is located at X 10560.670, Y 1931.161.) The node should offer four answers: Very helpful, Somewhat Helpful, Not very helpful, and Not helpful at all. Instead, it shows only the first three responses. 
![20210104_Emulator1](https://user-images.githubusercontent.com/69172956/103591972-e77df600-4eae-11eb-8a67-97fee1baff88.png)
Once selected, the responses that should appear on the following node appear on this node instead. 
![20210104_Emulator2](https://user-images.githubusercontent.com/69172956/103591991-f82e6c00-4eae-11eb-9027-e92d486d6bdf.png) 
This prevents the user from advancing the conversation. 
This issue doesn't seem to be present on other survey response questions in other files.

**Comment by danielanywhere** [comment]
This appears to be an effect of connecting the first output sockets to another node while leaving the remaining output sockets disconnected, as shown in the following source to the reported bug.
![2021010501-Scaffold](https://user-images.githubusercontent.com/11841524/103675495-3ffbd480-4f3d-11eb-90dd-0af56d35024b.png)
To repair this, make sure that any disconnected output socket still allows for a user input and feedback when there are no more connections in that chain.

**Comment by danielanywhere** [comment]
DEP20210105.1035 - An output socket with no connections is now allowed to accept user input from any position on the node.

**Comment by danielanywhere** [comment]
Released in version v0.2021.0105-alpha.preview.1.5a.
